apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: mpio
spec:
  selector:
    service: nginx
  ports:
    - name: nginx
      port: 80
      targetPort: 80
    - name: nginx-ssl
      port: 443
      targetPort: 443
  type: LoadBalancer