apiVersion: v1
kind: Service
metadata:
  name: certbot
  labels:
    app: mpio
spec:
  selector:
    service: certbot
  ports:
    - name: certbot
      port: 8080
      targetPort: 8080
    - name: certbot-dev
      port: 8081
      targetPort: 8081