apiVersion: v1
kind: Service
metadata:
  name: pgweb
  labels:
    app: mpio
spec:
  selector:
    service: pgweb
  ports:
    - name: pgweb
      port: 8081
      targetPort: 8081
  type: LoadBalancer