apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: mpio
    service: postgresql
spec:
  containers:
    - name: postgres
      image: "postgres:9.6"
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: password
        # -- end secret key ref -- #
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: api
              key: POSTGRES_DB