variables:
  ASSEMBLY_POINT: "${CI_PROJECT_DIR}"
  IMAGE_NAME: service-nfs

image-build-job:
  stage: build
  image:
    name: code.solern.com:5050/masterypath/devops-build-container:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  only:
    - master@masterypath/service-nfs
    - production@masterypath/service-nfs
  script:
    - source VERSION.env
    - docker info
    - export IMAGE_TAG="masterypath/${IMAGE_NAME}"
    - docker build --build-arg VERSION=${CURRENT_VERSION} -t $IMAGE_TAG ${ASSEMBLY_POINT}
    - docker login -u $GITLAB_DOCKER_USERNAME -p $GITLAB_DOCKER_ACCESS_TOKEN code.solern.com:5050
    - echo "--- BEGIN TESTS ---"
    - docker-compose down
    - docker-compose up -d
    - sleep 30
    - CONTAINER_ID=$(docker ps | grep 'client' | cut -d' ' -f 1)
    - docker exec $CONTAINER_ID mkdir /data
    - docker exec $CONTAINER_ID mount -t nfs4 nfs_server:/ /data
    - docker exec $CONTAINER_ID cat /data/hello.txt
    - docker-compose down
    - echo "--- / END TESTS ---"
    - docker tag $IMAGE_TAG code.solern.com:5050/${IMAGE_TAG}:latest
    - docker tag $IMAGE_TAG code.solern.com:5050/${IMAGE_TAG}:$CURRENT_VERSION
    - docker push code.solern.com:5050/${IMAGE_TAG}
    - doctl auth init --access-token ${DOCTL_TOKEN}
    - doctl registry login
    - docker tag $IMAGE_TAG registry.digitalocean.com/${IMAGE_TAG}:latest
    - docker tag $IMAGE_TAG registry.digitalocean.com/${IMAGE_TAG}:$CURRENT_VERSION
    - docker push registry.digitalocean.com/${IMAGE_TAG}

staging-deploy-job:
  stage: deploy
  dependencies:
    - image-build-job
  image:
    name: code.solern.com:5050/masterypath/devops-build-container:latest
  variables:
    PROD_OR_STAGING: staging
  only:
    - master@masterypath/service-nfs
  script:
    - source VERSION.env
    - doctl auth init --access-token ${DOCTL_TOKEN}
    - doctl kubernetes cluster kubeconfig save ${PROD_OR_STAGING}
    - cd deployment/${PROD_OR_STAGING}
    - cat nfs.yml.template | sed "s/{{VERSION}}/${CURRENT_VERSION}/g" > nfs.yml
    - kubectl apply -f nfs-block-storage-pvc.yml
    - kubectl apply -f nfs-pv.yml
    - kubectl apply -f nfs-pvc.yml
    - kubectl apply -f nfs-service.yml
    - kubectl apply -f nfs.yml