apiVersion: v1
kind: Service
metadata:
  name: jekyll
  labels:
    app: mpio
spec:
  selector:
    service: jekyll
  ports:
    - name: jekyll
      port: 8080
      targetPort: 8080
    - name: jekyll-debug
      port: 8081
      targetPort: 8081