apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-sites
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sites
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /sites
    server: 10.245.139.206
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-letsencrypt
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-letsencrypt
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /sites/certs/letsencrypt
    server: 10.245.139.206
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-conf
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-conf
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /conf
    server: 10.245.139.206
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-docker-images
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-docker-images
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /docker-images
    server: 10.245.139.206