apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-block-storage
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage