apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
spec:
  containers:
  - name: nfs-client
    image: ubuntu:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: nfsdata
      mountPath: "/data/"
  volumes:
  - name: nfsdata
    nfs:
      # https://stackoverflow.com/questions/49274655/kubernetes-cannot-mount-nfs-share-via-dns
      server: "10.245.139.206"
      path: "/"