apiVersion: v1
kind: Service
metadata:
  name: nfs
spec:
  selector:
    service: nfs
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111