#!/usr/bin/env bash
typeScriptFile="../client/src/api/models.ts"
sbt generateTypescript

perl -pi.bak -e 's/interface I/interface /g' $typeScriptFile
perl -pi.bak -e 's/: I/: /g' $typeScriptFile
perl -pi.bak -e 's/: ([\w+\[\]]+)/: $1;/g' $typeScriptFile
perl -pi.bak -e 's/^\s+$//g' $typeScriptFile
perl -pi.bak -e "s/\"/'/g" $typeScriptFile
perl -pi.bak -e 's/\)/);/g' $typeScriptFile

# dueDates: [string;, number][] -> dueDates: [string, number][];
perl -pi.bak -e 's/;,/,/g' $typeScriptFile
perl -pi.bak -e 's/\]\[\]/][];/g' $typeScriptFile

perl -pi.bak -e 's/export type (\w+) = (\w+)/export type $1 = $2;/g' $typeScriptFile
# Hack because I haven't gotten enums working with slick yet
perl -pi.bak -e 's/mode: string;/mode: MapMode;/g' $typeScriptFile

mv ${typeScriptFile} ${typeScriptFile}.tmp
echo "// *********** *********** ***********" > ${typeScriptFile}
echo "// Do not modify, this file is auto-generated by the scala back-end server." >> ${typeScriptFile}
echo "// If changes are needed to this file, modify locally, then submit an issue including your desired changes." >> ${typeScriptFile}
echo "// *********** *********** *********** \\\\" >> ${typeScriptFile}
cat ${typeScriptFile}.tmp >> ${typeScriptFile}

rm ${typeScriptFile}.bak
rm ${typeScriptFile}.tmp